In [1]:
# numpy的基本运算 #
import numpy as np

In [3]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [5]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [7]:
c = a - b
c

array([20, 29, 38, 47])

In [8]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [9]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [10]:
a < 35

array([ True,  True, False, False])

In [11]:
# 数组相乘
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [12]:
A * B

array([[2, 0],
       [0, 4]])

In [13]:
# 矩阵乘积
A.dot(B)

array([[5, 4],
       [3, 4]])

In [15]:
# 数组一元计算
a = np.random.random((2,3))
a

array([[0.26724748, 0.93348957, 0.76105214],
       [0.97385079, 0.25157313, 0.66420737]])

In [16]:
a.sum()

3.851420481585781

In [17]:
a.min()

0.2515731301753241

In [18]:
a.max()

0.9738507876266383

In [19]:
# 沿着某个轴操作
b = np.arange(12).reshape(3,4)

In [20]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b.sum(axis=0)  # sum of each column

array([12, 15, 18, 21])

In [22]:
b.sum(axis=1)  # sum of each row

array([ 6, 22, 38])

In [23]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [24]:
# 索引、切片和迭代 #

In [26]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [27]:
a[2]

8

In [28]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [29]:
a[2:5] = [3, 4, 5]

In [30]:
a

array([  0,   1,   3,   4,   5, 125, 216, 343, 512, 729], dtype=int32)

In [31]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,     4, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [32]:
def f(x, y):
    return 10 * x + y

In [34]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [35]:
b[2,3]

23

In [36]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [37]:
for e in b.flat:
    print(e)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
